### PR TITLE
Rename variables

### LINKED ISSUE #19: RFC: Proposed renaming scheme
# Proposed renaming scheme
Since we are going to start morphing the AddressBook soon, we should settle on a renaming scheme so work can be split up more easily. 
In our discussions, we used `Link` to replace `Person`, however I think a better name is needed to avoid confusion. 
Therefore, I'm proposing the following scheme, which tries to use similar terms as the [Atom feed specification](https://validator.w3.org/feed/docs/atom.html), and also tries to avoid naming conflicts with any of the libraries we are going to use.
Do give feedback or suggest how we can make this scheme better!

### Updates
25/2: move `siteName` into Link, change `feedLink` type to `Set<Link>`
24/2: change `Entries` to `EntryBook`

## Model
| **Old**                          | **New**                               |
| -------------------------------- | ------------------------------------- |
| (interface) ReadOnlyAddressBook | (interface) ReadOnlyEntryBook             |
| AddressBook                      | EntryBook                          |
| VersionedAddressBook             | VersionedEntryBook                 |
| UniquePersonList                 | UniqueEntryList                       |
| Person                           | Entry (currently “Link” as discussed) |

## Storage
| **Old**                         | **New**                     |
| ------------------------------- | --------------------------- |
| (interface) AddressBookStorage | (interface) EntryBookStorage |
| JsonAdaptedPerson               | JsonAdaptedEntry            |
| JsonAddressBookStorage          | JsonEntryBookStorage          |
| JsonSerializableAddressBook     | JsonSerializableEntryBook     |

## UI
| **Old**         | **New**        |
| --------------- | -------------- |
| PersonCard      | EntryCard      |
| PersonListPanel | EntryListPanel |

## Entry class (replaces Person class)
| **Identity fields**                                                                                            | **Data fields (all optional)**                                                                                                                                |
| -------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| link : Link<br>- require non-null<br>- isSame check only on this field | title : Title<br>- from Crux, usually headline of news article or HTML <title> tag content<br>- or user-overridden |
|                                                                                                                | tags : Set<Tag><br>- carried over                                                                                                                         |
|                                                                                                                | (future) comment: Comment<br>- user comments on the entry, e.g. why user saved the link                             
|                                                                                                                | (future) feedLinks: Set<Link><br>- added by Feeds component<br>- used to filter entries by feeds                                                              |
|                                                                                                                | (future) estimatedReadingTimeMinutes: Integer<br>- estimated reading time from Crux                                                                       |
|                                                                                                                | (future) description: String<br>- from Crux<br>- used if available, otherwise summary is generated                                                        |
|                                                                                                                | (future) heroImageLink : String<br>- from Crux<br>- url of hero image to be displayed in EntryCard                                                        |

### PR DESCRIPTION
**Pull request by thomastanck**
Resolves #19.

### CODE REVIEW

**Review by qjqqyy — APPROVED** [review]
it's renames

**Review by rlrh — APPROVED** [review]
LGTM

**Review by epicfailname — APPROVED** [review]
lgtm

**Comment by thomastanck** [comment]
Tri-tri-triple appr-appr-approval

**Pull request merged**
