### PR TITLE
Update UI to be more user-friendly

### LINKED ISSUE #161: The context is not obviously enough displayed
Responsible for:
* #139
* #140 
* #141
* #144 
* #145 
* #147
* #149

### LINKED ISSUE #177: UI is not user-friendly enough
#### Related to: #161 

Many peer testers are confused by the context system (#140, #141, #144).
This means that our UI is not user-friendly enough.
Some suggestions for UI improvement:
- Display the current context more clearly
- Show the ability to switch contexts more explicitly
- Add a navigation bar UI component to make the app hierarchy clearer and let users click to switch context

### PR DESCRIPTION
**Pull request by rlrh**
Resolves #161 
Resolves #177 

Ui

#### Summary of changes:
- Add navigation sidebar
  - 4 buttons for Reading List, Archives, Discover and Feeds match List, Archives, Results and Feeds context respectively
  - Executing a context-switching command highlights the button associated with the new context
  - Clicking a button executes the associated default command
    - Reading List: `list`
    - Archives: `archives`
    - Discover: `googlenews`
    - Feeds: `feeds`
- Redesign Entry cards
  - Make index display bigger and separate from title to support CLI-first policy
  - Move tags below title, description and link
- Use custom fonts
  - Roboto Light for body text
  - Roboto Slab for headings

### CODE REVIEW

**Comment by epicfailname** [comment]
There is a bug, though I cannot figure out what is causing it.
To reproduce:
1. Click `Archives` button
2. Enter `list` command
3. Click `Archives` button

The result display is not updated for step 3

**Comment by rlrh** [comment]
> There is a bug, though I cannot figure out what is causing it.
> To reproduce:
> 
> 1. Click `Archives` button
> 2. Enter `list` command
> 3. Click `Archives` button
> 
> The result display is not updated for step 3

Should be fixed with latest commit

**Comment by qjqqyy** [comment]
With reference to [this thread](https://stackoverflow.com/questions/34036207/javafx-could-not-load-font-face-font-because-of-com-sun-javafx-css-stylemanager), an issue in JavaFX's CSS font loader means that our custom font will not get loaded when there is a space character in the application path, like for example
```
Apr 11, 2019 2:07:01 AM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not load @font-face font [file:/C:/Users/Qi%20Ji/IdeaProjects/ab4/out/production/resources/fonts/RobotoSlab-Regular.ttf]
```
As this only happens in development under specific circumstances I suggest we don't bother working around it.

--------------

Note that running the `shadowJar` (or using the gradle task `runShadow`) works.

**Comment by rlrh** [comment]
> With reference to [this thread](https://stackoverflow.com/questions/34036207/javafx-could-not-load-font-face-font-because-of-com-sun-javafx-css-stylemanager), an issue in JavaFX's CSS font loader means that our custom font will not get loaded when there is a space character in the application path, like for example
> 
> ```
> Apr 11, 2019 2:07:01 AM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
> INFO: Could not load @font-face font [file:/C:/Users/Qi%20Ji/IdeaProjects/ab4/out/production/resources/fonts/RobotoSlab-Regular.ttf]
> ```
> As this only happens in development under specific circumstances I suggest we don't bother working around it.
> 
> Note that running the `shadowJar` (or using the gradle task `runShadow`) works.

Thanks for this! Fortunately in this case it still fails gracefully by reverting to a default system font.

**Review by thomastanck — APPROVED** [review]
Good PR, good design.

**Pull request merged**
