### PR TITLE
Remove sample data on startup

### LINKED ISSUE #156: Initial loading of default feeds are not available for offline reading
**Describe the bug**
The feeds that were added at load are not saved in the articles folder
**To Reproduce**
1. Turn off internet connection 
2. Click on a feed
3. See error in display: The page cannot be displayed

**Expected behavior**
Since the articles are available for offline viewing, disconnecting the computer from the internet still allows us to view the articles. However the page cannot be displayed.

**Screenshots**

image

<hr>

**Reported by:** @jing1324
**Severity:** Low

<sub>[original: nus-cs2103-AY1819S2/pe-dry-run#939]</sub>

### PR DESCRIPTION
**Pull request by thomastanck**
Resolves #156 by not having any initial data.

### CODE REVIEW

**Comment by rlrh** [comment]
Should we have one entry so the UI doesn't look so barren?
Since when it is inevitably selected, it gets downloaded anyway.

**Comment by qjqqyy** [comment]
> 
> 
> Should we have one entry so the UI doesn't look so barren?
> Since when it is inevitably selected, it gets downloaded anyway.

Unfortunately that means we have to ship the jar with the data folder, or hardcode the entry's contents somehow. Or else the user can still start the application for the first time while offline and reproduce #156

**Comment by qjqqyy** [comment]
An alternative approach would be to start the sample entrybook with our user guide, which is accessible via
`jar:file:/path/to/README.jar!/docs/HelpWindow.html`

**Comment by rlrh** [comment]
> > Should we have one entry so the UI doesn't look so barren?
> > Since when it is inevitably selected, it gets downloaded anyway.
> 
> Unfortunately that means we have to ship the jar with the data folder, or hardcode the entry's contents somehow. Or else the user can still start the application for the first time while offline and reproduce #156

I see, I think it's better to remove the sample data then.

**Review by qjqqyy — APPROVED** [review]
We can probably resolve this in a more sophisticated way in the future.

**Pull request merged**
